PortForward:
 - Name: nginx1
   Resource: deployment/nginx  # 资源类型：deployment/nginx  工作负载名称
   LocalPort: 8081             # 本地监听端口
   RemotePort: 80              # 容器内监听端口
 - Name: nginx2
   Resource: deployment/nginx  # 资源类型：deployment/nginx  工作负载名称
   LocalPort: 8082             # 本地监听端口
   RemotePort: 80              # 容器内监听端口